# Generated by Django 5.1.1 on 2024-09-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_movies_released_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='movies',
            name='gerne',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='summary',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Gerne',
        ),
    ]
